"""Plan the FINAL training runs - the ones whose test set will be scored.

    python scripts/final_queue.py --seeds 0 1 2 --gpus 0 1 3

THIS IS NOT scripts/dev_queue.py AND MUST NOT BECOME IT. That file says, in its own
docstring, that no reported test set is ever scored from it, and the separation is the
reason this repository exists: scPKFM scored its test set thirteen times while selecting
and none of its numbers could be read afterwards. Everything selected so far - the
whitened observables, the dense readout, the calibration's exponent, the epoch count, the
loss weights - was chosen on validation folds. These runs change nothing and select
nothing. They train the settled configuration on the real splits so that
scripts/final_table.py can score the test ONCE.

WHAT IS TRAINED, and which reported block each one produces:

    norman   method=additive       folds 0-4    Table 1
    norman   method=combinations   folds 0-4    Table 2, both the Single and Double blocks
    combosciplex  the scDFM list split          Table 3

Norman's reported numbers are means over five folds. Validation only ever had ONE Norman
fold - NORMAN_VALIDATION is defined for fold 0 alone - so the fold-to-fold transfer that
combosciplex showed (a global scale losing nearly half its value between folds) has never
been checked there. That is a real risk carried into these runs and it is stated rather
than hidden.

EVERY FOLD NEEDS ITS OWN CACHE because data.exclude_test_from_hvg makes the gene space
depend on which conditions are held out. The cache name carries dataset, method and fold
for that reason; scPKFM silently reused one across splits.
"""

from __future__ import annotations

import argparse
import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# The configuration every final run uses. Settled on validation; see docs/FINDINGS.md.
SETTLED = [
    "model.readout=dense",
    "model.observable_whiten=zca",
    "train.gene_endpoint_weight=10",
    "train.epochs=100",
]

DATA = {
    "norman": ["data.raw_h5ad=data/norman/norman.h5ad",
               "data.n_hvg=5000", "data.hvg_criterion=scanpy",
               "split.source=reference_pkl"],
    "combosciplex": ["data.raw_h5ad=data/combosciplex/combosciplex.h5ad",
                     "data.control_label=control",
                     "data.normalise_from_counts=counts",
                     "data.n_hvg=5000", "data.hvg_criterion=scanpy",
                     "split.source=list"],
}

# (dataset, method, folds, which reported block it produces)
TARGETS = [
    ("norman", "additive", range(5), "Table 1 Norman additive"),
    ("norman", "combinations", range(5), "Table 2 Single + Double"),
    ("combosciplex", "list", [0], "Table 3 ComboSciPlex"),
]


def plan(seeds: list[int], gpus: list[int]) -> list[dict]:
    jobs = []
    for dataset, method, folds, block in TARGETS:
        for fold in folds:
            cache = f"assets/final_{dataset}_{method}_fold{fold}.h5ad"
            overrides = list(DATA[dataset]) + [f"data.cache_h5ad={cache}",
                                               f"split.fold={fold}"]
            if dataset == "norman":
                overrides.append(f"split.method={method}")
            overrides += SETTLED
            for seed in seeds:
                jobs.append({
                    "kind": "final", "block": block,
                    "tag": f"final_{dataset}_{method}_f{fold}_s{seed}",
                    "dataset": dataset, "method": method, "fold": fold,
                    "seed": seed, "cache": cache,
                    "overrides": overrides + [f"train.seed={seed}"],
                })
    for index, job in enumerate(jobs):
        job["gpu"] = gpus[index % len(gpus)]
    return jobs


def write(jobs: list[dict], gpus: list[int], out_dir: str) -> None:
    os.makedirs(out_dir, exist_ok=True)
    caches = sorted({job["cache"] for job in jobs})
    for gpu in gpus:
        mine = [job for job in jobs if job["gpu"] == gpu]
        lines = ["#!/bin/sh",
                 "# Generated by scripts/final_queue.py. These are the runs whose TEST set",
                 "# will be scored, once, by scripts/final_table.py.",
                 f"# {len(mine)} runs on GPU {gpu}.",
                 "set -e", ""]
        if gpu == gpus[0]:
            lines += ["# Caches first, on this queue only; the others wait. Building the",
                      "# same cache twice in parallel is how two runs read a half-written",
                      "# file.", ""]
            for cache in caches:
                job = next(j for j in jobs if j["cache"] == cache)
                data_overrides = " ".join(o for o in job["overrides"]
                                          if o.startswith(("data.", "split.")))
                lines += [f'if [ ! -f "{cache}" ]; then',
                          f'  python data_prepare.py --set {data_overrides}',
                          "fi", ""]
        else:
            lines += [f"# Wait for the caches GPU {gpus[0]}'s queue builds.", ""]
            for cache in caches:
                lines += [f'while [ ! -f "{cache}" ]; do sleep 30; done', ""]
        for job in mine:
            checkpoint = f'results/runs/{job["tag"]}/checkpoint.pt'
            lines += [f'if [ -f "{checkpoint}" ]; then',
                      f'  echo "=== {job["tag"]} (done, skipping) ==="',
                      "else",
                      f'  echo "=== {job["tag"]} ==="',
                      f'  CUDA_VISIBLE_DEVICES={gpu} python scripts/train.py '
                      f'--tag {job["tag"]} --set {" ".join(job["overrides"])}',
                      "fi", ""]
        path = os.path.join(out_dir, f"gpu{gpu}.sh")
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write("\n".join(lines))
        os.chmod(path, 0o755)

    with open(os.path.join(out_dir, "manifest.json"), "w", encoding="utf-8") as handle:
        json.dump({"name": "final", "settled": SETTLED, "jobs": jobs}, handle, indent=2)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--seeds", nargs="+", type=int, default=[0, 1, 2])
    parser.add_argument("--gpus", nargs="+", type=int, required=True)
    args = parser.parse_args()

    jobs = plan(args.seeds, args.gpus)
    out_dir = os.path.join("results", "final")
    write(jobs, args.gpus, out_dir)

    print(f"{len(jobs)} FINAL runs over {len(args.gpus)} GPUs -> {out_dir}")
    print(f"  settled configuration: {' '.join(SETTLED)}")
    for dataset, method, folds, block in TARGETS:
        n = sum(1 for j in jobs if j["dataset"] == dataset and j["method"] == method)
        print(f"  {block:28s} {dataset}/{method}, {len(list(folds))} folds, {n} runs")
    for gpu in args.gpus:
        print(f"  sh {os.path.join(out_dir, f'gpu{gpu}.sh')}  "
              f"({sum(1 for j in jobs if j['gpu'] == gpu)} runs)")
    print("\nThese runs select nothing. When they finish, the test set is scored ONCE:")
    print("  python scripts/final_table.py results/final/manifest.json "
          "--calibration <from dev_rule --fit-all> --score-the-test")


if __name__ == "__main__":
    main()
